// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_e9879a1565935453499d015faae62da8_png);   // assets/e9879a1565935453499d015faae62da8.png
LV_IMG_DECLARE( ui_img_1912175_png);   // assets/1912175.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
