// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT eventRotate

lv_obj_t *ui_eventRotate_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_eventRotate;
cui_eventRotate = lv_btn_create(comp_parent);
lv_obj_set_width( cui_eventRotate, 100);
lv_obj_set_height( cui_eventRotate, 50);
lv_obj_set_x( cui_eventRotate, 14 );
lv_obj_set_y( cui_eventRotate, -68 );
lv_obj_set_align( cui_eventRotate, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_eventRotate, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_eventRotate, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_EVENTROTATE_NUM);
children[UI_COMP_EVENTROTATE_EVENTROTATE] = cui_eventRotate;
lv_obj_add_event_cb(cui_eventRotate, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_eventRotate, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_eventRotate_create_hook(cui_eventRotate);
return cui_eventRotate; 
}

